name: Deploy site

on:
  push:
    branches:
      - master
    paths-ignore:
      - README.md
      - LICENSE

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 16.x ]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm test
    - run: git config --global user.email cuprumzhen@gmail.com
    - run: git config --global user.name cuprumz
    - shell: bash
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN}}
      run: npm run deploy
